### ISSUE TITLE
Too much space before 'Opening programme' in top menu

### ISSUE THREAD

**Issue by pwrstudio** [pwrstudio/rfgen#42]

**Comment by pwrstudio** [comment]
Thanks @manegame !
But would it be possible to reduce the space, to something like this:

<img width="1100" alt="Screenshot 2019-10-23 at 18 54 33" src="https://user-images.githubusercontent.com/8209990/67416288-e244cc00-f5c6-11e9-993f-41b191201a3a.png">

Sot hat opening programme gets less, rather than the others more.

thx

**Comment by manegame** [comment]
@pwrstudio fixed now?
