### ISSUE TITLE
Wrong color gradient in menu on iPhone

### ISSUE THREAD

**Issue by pwrstudio** [pwrstudio/rfgen#53]
<img width="420" alt="Screenshot 2019-10-27 at 12 13 08" src="https://user-images.githubusercontent.com/8209990/67633696-57f4b480-f8b3-11e9-93e2-db9d1376c9c3.png">
<img width="427" alt="Screenshot 2019-10-27 at 12 12 10" src="https://user-images.githubusercontent.com/8209990/67633697-57f4b480-f8b3-11e9-97ef-54edb47670ef.png">

**Comment by manegame** [comment]
Checking it

**Comment by manegame** [comment]
@pwrstudio where are you testing?

**Comment by pwrstudio** [comment]
Browserstack! Can send you login info  in a sec..

**Comment by manegame** [comment]
No worries. I just found out it's a Safari issue. Is css auto-prefixed?

**Comment by pwrstudio** [comment]
RE: auto-prefix: dont think so! feel free to add to the rollup production build.

**Comment by manegame** [comment]
Will check it

**Comment by manegame** [comment]
Note: The gradient works, but the middle renders as if we're going to a transparent black. We have to transition from the color's rgb values to the color's rgba values. (according to [this answer](https://stackoverflow.com/a/30674347/5934781))
